/* CVS $Id: $ */
package edu.mit.simile.vocabularies; 
import org.openrdf.model.*;
import org.openrdf.model.impl.*;
import org.openrdf.repository.*;
import org.openrdf.repository.sail.*;
import org.openrdf.sail.memory.MemoryStore;
 
/**
 * Vocabulary definitions from file:./ontologies/facets.owl 
 * @author Auto-generated by schemagen on 07 Mar 2008 21:56 
 */
public class Facets {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Repository m_model;
    static {
    	try {
    			m_model = new SailRepository(new MemoryStore());
    			m_model.initialize();
    		} catch (RepositoryException e) {
    			System.err.println("Failed to initialize");
    		}
    }
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.getValueFactory().createURI( NS );
    
    /** <p></p> */
    public static final URI facets = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#facets" );
    
    /** <p></p> */
    public static final URI hides = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#hides" );
    
    /** <p></p> */
    public static final URI types = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#types" );
    
    /** <p></p> */
    public static final Resource Facet = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#Facet" );
    
    /** <p></p> */
    public static final Resource FacetList = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#FacetList" );
    
    /** <p></p> */
    public static final Resource FacetSet = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#FacetSet" );
    
    /** <p></p> */
    public static final Resource TypeList = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#TypeList" );
    
    /** <p></p> */
    public static final Resource allTypes = m_model.getValueFactory().createURI( "http://simile.mit.edu/2006/01/ontologies/fresnel-facets#allTypes" );
    
}
