/* CVS $Id: $ */
package edu.mit.simile.vocabularies; 
import org.openrdf.model.*;
import org.openrdf.model.impl.*;
import org.openrdf.repository.*;
import org.openrdf.repository.sail.*;
import org.openrdf.sail.memory.MemoryStore;
 
/**
 * Vocabulary definitions from file:./ontologies/extended.owl 
 * @author Auto-generated by schemagen on 07 Mar 2008 21:56 
 */
public class FresnelExtended {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Repository m_model;
    static {
    	try {
    			m_model = new SailRepository(new MemoryStore());
    			m_model.initialize();
    		} catch (RepositoryException e) {
    			System.err.println("Failed to initialize");
    		}
    }
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/09/fresnel#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.getValueFactory().createURI( NS );
    
    /** <p></p> */
    public static final URI alternateProperties = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#alternateProperties" );
    
    /** <p></p> */
    public static final URI mergeProperties = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#mergeProperties" );
    
    /** <p></p> */
    public static final URI moreDetailsFor = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#moreDetailsFor" );
    
    /** <p></p> */
    public static final URI stylesheetLink = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#stylesheetLink" );
    
    /** <p></p> */
    public static final URI active = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#active" );
    
    /** <p></p> */
    public static final URI contentReplace = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentReplace" );
    
    /** <p></p> */
    public static final URI firstLetter = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#firstLetter" );
    
    /** <p></p> */
    public static final URI focus = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#focus" );
    
    /** <p></p> */
    public static final URI hover = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#hover" );
    
    /** <p></p> */
    public static final URI link = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#link" );
    
    /** <p></p> */
    public static final URI visited = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#visited" );
    
    /** <p></p> */
    public static final URI containerStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#containerStyle" );
    
    /** <p></p> */
    public static final URI displayAs = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#displayAs" );
    
    /** <p></p> */
    public static final Resource PropertyDescription = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#PropertyDescription" );
    
    /** <p></p> */
    public static final Resource animation = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#animation" );
    
    /** <p></p> */
    public static final Resource audio = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#audio" );
    
    /** <p></p> */
    public static final Resource fslSelector = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#fslSelector" );
    
    /** <p></p> */
    public static final Resource html = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#html" );
    
    /** <p></p> */
    public static final Resource labelOfParent = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#labelOfParent" );
    
    /** <p></p> */
    public static final Resource print = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#print" );
    
    /** <p></p> */
    public static final Resource projection = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#projection" );
    
    /** <p></p> */
    public static final Resource screen = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#screen" );
    
    /** <p></p> */
    public static final Resource sparqlSelector = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#sparqlSelector" );
    
    /** <p></p> */
    public static final Resource styleClass = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#styleClass" );
    
    /** <p></p> */
    public static final Resource stylingInstructions = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#stylingInstructions" );
    
    /** <p></p> */
    public static final Resource text = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#text" );
    
    /** <p></p> */
    public static final Resource textstream = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#textstream" );
    
    /** <p></p> */
    public static final Resource video = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#video" );
    
}
