/* CVS $Id: $ */
package edu.mit.simile.vocabularies; 
import org.openrdf.model.*;
import org.openrdf.model.impl.*;
import org.openrdf.repository.*;
import org.openrdf.repository.sail.*;
import org.openrdf.sail.memory.MemoryStore;
 
/**
 * Vocabulary definitions from file:./ontologies/core.owl 
 * @author Auto-generated by schemagen on 07 Mar 2008 21:56 
 */
public class FresnelCore {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Repository m_model;
    static {
    	try {
    			m_model = new SailRepository(new MemoryStore());
    			m_model.initialize();
    		} catch (RepositoryException e) {
    			System.err.println("Failed to initialize");
    		}
    }
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2004/09/fresnel#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.getValueFactory().createURI( NS );
    
    /** <p></p> */
    public static final URI classFormatDomain = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#classFormatDomain" );
    
    /** <p></p> */
    public static final URI classLensDomain = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#classLensDomain" );
    
    /** <p></p> */
    public static final URI group = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#group" );
    
    /** <p></p> */
    public static final URI hideProperties = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#hideProperties" );
    
    /** <p></p> */
    public static final URI instanceFormatDomain = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#instanceFormatDomain" );
    
    /** <p></p> */
    public static final URI instanceLensDomain = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#instanceLensDomain" );
    
    /** <p></p> */
    public static final URI label = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#label" );
    
    /** <p></p> */
    public static final URI labelFormat = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#labelFormat" );
    
    /** <p></p> */
    public static final URI primaryClasses = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#primaryClasses" );
    
    /** <p></p> */
    public static final URI property = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#property" );
    
    /** <p></p> */
    public static final URI propertyFormat = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#propertyFormat" );
    
    /** <p></p> */
    public static final URI propertyFormatDomain = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#propertyFormatDomain" );
    
    /** <p></p> */
    public static final URI purpose = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#purpose" );
    
    /** <p></p> */
    public static final URI resourceFormat = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#resourceFormat" );
    
    /** <p></p> */
    public static final URI showProperties = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#showProperties" );
    
    /** <p></p> */
    public static final URI sublens = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#sublens" );
    
    /** <p></p> */
    public static final URI use = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#use" );
    
    /** <p></p> */
    public static final URI value = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#value" );
    
    /** <p></p> */
    public static final URI valueFormat = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#valueFormat" );
    
    /** <p></p> */
    public static final URI contentAfter = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentAfter" );
    
    /** <p></p> */
    public static final URI contentBefore = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentBefore" );
    
    /** <p></p> */
    public static final URI contentFirst = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentFirst" );
    
    /** <p></p> */
    public static final URI contentLast = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentLast" );
    
    /** <p></p> */
    public static final URI contentNoValue = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#contentNoValue" );
    
    /** <p></p> */
    public static final URI depth = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#depth" );
    
    /** <p></p> */
    public static final URI labelStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#labelStyle" );
    
    /** <p></p> */
    public static final URI propertyStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#propertyStyle" );
    
    /** <p></p> */
    public static final URI resourceStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#resourceStyle" );
    
    /** <p></p> */
    public static final URI valueStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#valueStyle" );
    
    /** <p></p> */
    public static final Resource ClassList = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#ClassList" );
    
    /** <p></p> */
    public static final Resource ConvenienceToken = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#ConvenienceToken" );
    
    /** <p></p> */
    public static final Resource ConvienceProperty = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#ConvienceProperty" );
    
    /** <p></p> */
    public static final Resource Format = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#Format" );
    
    /** <p></p> */
    public static final Resource FormatDescription = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#FormatDescription" );
    
    /** <p></p> */
    public static final Resource FormatDescriptionNoSubstitution = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#FormatDescriptionNoSubstitution" );
    
    /** <p></p> */
    public static final Resource FormatDescriptionSubstitution = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#FormatDescriptionSubstitution" );
    
    /** <p></p> */
    public static final Resource Group = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#Group" );
    
    /** <p></p> */
    public static final Resource HidePropertyList = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#HidePropertyList" );
    
    /** <p></p> */
    public static final Resource LabellingFormat = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#LabellingFormat" );
    
    /** <p></p> */
    public static final Resource Lens = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#Lens" );
    
    /** <p></p> */
    public static final Resource PropertyDescription = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#PropertyDescription" );
    
    /** <p></p> */
    public static final Resource PropertySet = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#PropertySet" );
    
    /** <p></p> */
    public static final Resource PropertyValueStyle = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#PropertyValueStyle" );
    
    /** <p></p> */
    public static final Resource Purpose = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#Purpose" );
    
    /** <p></p> */
    public static final Resource ShowPropertyList = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#ShowPropertyList" );
    
    /** <p></p> */
    public static final Resource allProperties = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#allProperties" );
    
    /** <p></p> */
    public static final Resource defaultLens = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#defaultLens" );
    
    /** <p></p> */
    public static final Resource externalLink = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#externalLink" );
    
    /** <p></p> */
    public static final Resource image = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#image" );
    
    /** <p></p> */
    public static final Resource labelLens = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#labelLens" );
    
    /** <p></p> */
    public static final Resource member = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#member" );
    
    /** <p></p> */
    public static final Resource none = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#none" );
    
    /** <p></p> */
    public static final Resource replacedResource = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#replacedResource" );
    
    /** <p></p> */
    public static final Resource show = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#show" );
    
    /** <p></p> */
    public static final Resource uri = m_model.getValueFactory().createURI( "http://www.w3.org/2004/09/fresnel#uri" );
    
}
